apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: smart-admin-event-listener-api-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: smart-admin-event-listener-api